### ISSUE TITLE
Most themes are incompatible with window-buttons-applet

### ISSUE THREAD

**Issue by zoomer296** [ubuntu-mate/mate-window-applets#1]
So far, Arc, Numix, and one other that I forgot but will find when I retest haven't worked. I'll poke around and see if I can figure out what causes it, but be advised that I have no clue what I'm doing.

**Comment by zoomer296** [comment]
I just found out that window-buttons-applet gets its icons from "/usr/share/icons/mate-window-applets". That should probably go in a readme, man page, or something.

Is there any way to get them directly from the theme?

**Comment by MaickonPrebianca** [comment]
I created a copy the path structure and put my svg icon
![image](https://user-images.githubusercontent.com/29361602/45396108-fc645a80-b60f-11e8-8260-c8728d190844.png)

![image](https://user-images.githubusercontent.com/29361602/45396129-0d14d080-b610-11e8-94a9-0375947dbf52.png)

![image](https://user-images.githubusercontent.com/29361602/45396157-2f0e5300-b610-11e8-8940-a01611d11102.png)

Result
![image](https://user-images.githubusercontent.com/29361602/45396199-67ae2c80-b610-11e8-9875-2491fd42385a.png)

**Comment by flexiondotorg** [comment]
Ideally, mate-window-applets should automatically use the window controls buttons from the currently selected theme rather than relying on its own icon themes.

@gabrielfin Thank you for your recent contributions to this project! Do you want to have a go at fixing this issue to? :smiley:

**Comment by gabrielfin** [comment]
I would love to, but I'm not sure how. I tried setting the search path of `Gtk.IconTheme` to `/usr/share/themes/` but it doesn't work. I guess it's because those themes are not defined as icon themes, but as regular GTK themes...

In that case, the only other solution I can think of is to not use `Gtk.IconTheme`, but instead make my own "icon finder" function. Is that reasonable? Is there a better way?

**Comment by gabrielfin** [comment]
@flexiondotorg So, I've been working on an "icon finder" solution. A couple of questions:

What should we do if the selected theme does not contain any image icons (for example, HighContrast)?
- Hide all buttons and show a dialog with an error message?
- Show a fallback theme (Black?, Ambiant-MATE?) and a dialog with an error message?
- Silently show a fallback theme?
- Other?

Are we still going to offer the option to set the theme by hand, or should we simply use whatever `/org/mate/marco/general/theme` says?

**Comment by flexiondotorg** [comment]
Thank you for working on this! 😀 

I don't think there should be a user configurable option to set the theme, it should use whatever the current Marco windows controls offer.

Where Marco is missing icons, perhaps we should  just ship a default set to fallback to.

**Comment by flexiondotorg** [comment]
Closed via #15

**Comment by tmarkov** [comment]
> I don't think there should be a user configurable option to set the theme, it should use whatever the current Marco windows controls offer.

Many themes set different styles for window borders and panel. In those situations, it's often the case that the icons applicable for window borders don't look well (or are outright invisible) on the panel applet. For example, Qogir-light (https://www.mate-look.org/p/1230631/) ends up with invisible dark icons on black panel.

**Comment by gabrielfin** [comment]
In that case, you should create a folder in `~/.icons/mate-window-applets/Qogir-light` with the icons from the dark variant. You can probably just copy everything from `Quogir-dark/metacity-1`

This is a weird theme, because even though everything is light, the panels are dark. Is that a common thing?
