### ISSUE TITLE
[window-buttons-applet] Add option to control the background window when current window is not maximized

### ISSUE THREAD

**Issue by gabrielfin** [ubuntu-mate/mate-window-applets#10]
Add a third option to "Control only maximized windows" so that when the current window is not maximized, the window-buttons-applet controls the maximized window which is behind the current one (i.e. the last maximized window), instead of hiding the buttons. Also, the buttons should look "unfocused".
This is similar to how regular windows work. And also how Gnome's window-buttons applet works.

Also (perhaps this should be a separate issue), "Control only maximized windows" should be implemented in window-menu-applet and window-title-applet as well.

**Comment by flexiondotorg** [comment]
Closed via #11
