### ISSUE TITLE
MATE Windows Applets 19.10.1 FTBFS

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/mate-window-applets#16]
@gabrielfin MATE Windows Applets 19.10.1 fails to build from source. Please can you take a look, here is a build log:

  * <https://launchpadlibrarian.net/429241482/buildlog_ubuntu-disco-amd64.mate-window-applets_19.10.1-0ubuntu1~disco1.0_BUILDING.txt.gz>

**Comment by gabrielfin** [comment]
Weird, it compiled fine in Bionic... Anyway, made some changes and recompiled in Disco, and the errors are now gone.

PS: Whitespace was auto-trimmed, sorry...
PS 2: FYI, I discovered a couple of bugs which I'll be fixing in the next days

**Comment by flexiondotorg** [comment]
Closed via #17.
