### ISSUE TITLE
The window buttons are a bit blurry.

### ISSUE THREAD

**Issue by simurgh9** [ubuntu-mate/mate-window-applets#24]
Here are the window buttons in a usual window decoration:
![good](https://user-images.githubusercontent.com/43047754/95025330-83992680-064e-11eb-919b-8ba75797fe4f.png)
Here are the buttons in the window applet:
![bad](https://user-images.githubusercontent.com/43047754/95025347-9ad81400-064e-11eb-8f19-8006549e8aaa.png)

As you can see, the latter are a bit blurry. I am using the arc-dark theme. Is there any remedy to this?

**Comment by gabrielfin** [comment]
Yes, you need to tweak the spacing and padding in the settings

**Comment by simurgh9** [comment]
I am somewhat new to Mate, mind showing an example or pointing to a resource where that is shown?

**Comment by gabrielfin** [comment]
Right click on the applet and you'll get a menu with the "Settings" option. Click on it and a dialog will open where you can try different values for padding and spacing.

**Comment by simurgh9** [comment]
Putting the size of mate-panel at 28 px, padding at 4 px and size at 3 px fixed it for me. Why does this happen though? Aren't the decorations being rendered present in `.svg`?

**Comment by gabrielfin** [comment]
Try with a mate-panel of height 24px and padding of 0px. At least in my case Arc theme (which is what you are using, right?) looks sharp with those settings.

I think the blurriness was fixed in more recent versions of Mate. Which version are you using?

**Comment by simurgh9** [comment]
Yeah, I am using arc-theme. System monitor says I am on "MATE 1.24.0" and Ubuntu is at 20.04.1.

**Comment by tmarkov** [comment]
Mine are blurry, too, and I can't get around that by tweaking settings (only make it slightly less blurry). I'm using 2x scaling for HiDPI, and my guess is that's causing the problem for me.

**Comment by gabrielfin** [comment]
I may have found a possible solution. I'll make a PR in a few days.

**Comment by simurgh9** [comment]
Any progress?

**Comment by gabrielfin** [comment]
Yes. @simurgh9 and @tmarkov, would you please let me know if your issue is solved with [this branch](/gabrielfin/mate-window-applets/tree/blurry-fix)?

**Comment by tmarkov** [comment]
Just tested it, it works great! Thanks :). And, if you're celebrating, happy holidays!

**Comment by simurgh9** [comment]
This is a noob question but will an `apt update` fetch your fix?

**Comment by tmarkov** [comment]
@simurgh9 No, the idea is to test it and make sure it works before it's released. So you will need to get the updated source code and manually build and install it.

I would first remove the package from the repo (I'm not sure if that's necessary, but just in case): `sudo apt install mate-window-buttons-applet mate-window-menu-applet mate-window-title-applet`.

Also, you need to have these installed for the build to work: git, meson, ninja, vala, Gtk3, Gdk3, libwnck3

Finally, to get the code and install it, run in some working directory:
```
git clone https://github.com/gabrielfin/mate-window-applets.git
cd mate-window-applets
meson --prefix=/usr build
cd build
ninja
sudo ninja install
cd ..
sudo ./install-icons.sh install
sudo glib-compile-schemas /usr/share/glib-2.0/schemas
```

**Comment by gabrielfin** [comment]
To install the full set of dependencies I think you have to run `sudo apt install meson ninja-build valac libwnck-3-dev libgtk-3-dev libgdk-pixbuf2.0-dev libmate-panel-applet-dev`

The fix is in separate branch, so instead of
```
git clone https://github.com/gabrielfin/mate-window-applets.git
```
it should be
```
git clone -b blurry-fix https://github.com/gabrielfin/mate-window-applets.git
```

**Comment by simurgh9** [comment]
Alright, sorry about being *extra* late. I followed your directions and yes, the buttons are a bit less blurry but still not like they look in the window decoration. BTW, the indicator applet and the brisk menu's icons are also blurry. Honestly, everything about mate-panel is a [mess](https://ubuntu-mate.community/t/mate-panel-does-not-run-after-boot/23589?u=simurgh9). I don't understand how can such a central widget to the DE be so buggy.

**Comment by simurgh9** [comment]
A word of caution: I ran `sudo apt autoremove` which removed `mate-window-applets-common` and that broke the buttons. I had to install it again with `sudo apt install mate-window-applets-common`.

**Comment by Zetta1-Reid0** [comment]
Hello . I am the original author of the Applets .
The reason for the blur is actually the "filtering" . When setting the icon for the button if interp. type is changed from Gdk.InterpType.HYPER to Gdk.InterpType.NEAREST it should almost eliminate the blur but at big panel sizes the icons will look pixelated.
For it to be absolutely gone I can think of these solutions : 
1.Use diffirent images with diffirent scale for different panel sizes and not scale them at all. That would also eliminate the padding option.
2.Use vector images for themes.
@simurgh9 The buttons applet uses separate themes from Marco . That is becouse Marco parses theme files , therefore it doesn't aways use images for it's decoration. As for CSD images , when I started this CSD were more of a Gnome thing so I never considered them a thing.

**Comment by simurgh9** [comment]
> 2.Use vector images for themes.

So you're saying that the arch theme is not using vector images?

> The buttons applet uses separate themes from Marco .

What Macro? I am sorry, I might not be all caught up on the lingo here.

**Comment by Zetta1-Reid0** [comment]
My mistake . It seems they updated it to use icons from Marco themes . ( should read whole source code next time ) 
Also I don't know what Macro are you talking about. In your quote it really says Marco . Also Marco is the window manager of Mate Desktop Environment .

**Comment by gabrielfin** [comment]
simurgh9 said other icons in mate-panel are also blurry, so it might be a general Mate issue. @simurgh9, maybe you could open an issue in https://github.com/mate-desktop/mate-panel/ ?

**Comment by simurgh9** [comment]
Oh, I was definitely reading Marco as macro lol. I don't know what details to provide if I open an issue there. In any event, the blurriness of things in the panel is no secret. You can look that up on their community website and find tons of cousin issues reported.

Another instance is the icon of the brisk menu. It also gets blurry when the panel is not a specified size.
