### ISSUE TITLE
Change buttons app when moving to another workspace

### ISSUE THREAD

**Issue by piranna** [ubuntu-mate/mate-window-applets#28]
If I have configured `mate-window-applets` to follow current maximized window, and I move to another workspace, the buttons are still the ones from the maximized window in the previous workspace. They should be the buttons of the windows in the current workspace only, if not then you could be closing an app from another workspace, that's annoying.

**Comment by gabrielfin** [comment]
Are you using the latest version? This was added in version 21.04
If you are, then are you using Compiz or Marco? Wich of the 3 "Behaviour" are you using in Settings?

**Comment by flexiondotorg** [comment]
Closing due to no feedback and the feature is implemented since 21.04

**Comment by piranna** [comment]
I have totally missed the response. Yes, I'm always using latest version (right now, 21.10 installed fresh), I use Marco window manager, and I'm using the behaviour to follow current top level window only if maximized.
