### ISSUE TITLE
[BUG] Huge memory leak in window title applet.

### ISSUE THREAD

**Issue by aero31aero** [ubuntu-mate/mate-window-applets#4]
I was unable to get a lot of data as my priority was to stop the process. The following is the output on my 4GB RAM laptop with the window-title applet using 84% of memory.

```
$ ps -e --sort=-%mem -o pid,ppid,cmd,%mem,%cpu| head
  PID  PPID CMD                         %MEM %CPU
24866  2141 /usr/lib/mate-applets/mate- 84.3  4.7
 1610  1579 /usr/lib/xorg/Xorg -core :0  0.4  1.6
 2974  2176 /usr/bin/python3 /usr/bin/g  0.4  0.6
 2746  2141 /usr/lib/mate-indicator-app  0.2  0.0
 2700  2176 mate-panel                   0.2  0.1
 2738  2141 /usr/lib/mate-panel/clock-a  0.2  0.0
 2778  2176 compiz                       0.2  0.9
 3115  3114 /usr/bin/gtk-window-decorat  0.2  0.0
 2922  2176 plank                        0.2  0.0
````

**Comment by MMachado-uy** [comment]
Same here.
Just took all my Ram and Swap before throwing an error.
![problem in window-title-applet_866](https://user-images.githubusercontent.com/15673255/43523081-a55b20d4-9571-11e8-94d0-9e9e8f127499.png)

Dell Latitude 7450, 8GB RAM

**Comment by MGdesigner** [comment]
Same here. I captured my top:
![window-title-applet-big-memoryleak](https://user-images.githubusercontent.com/4480740/43848120-dbd31ac4-9b64-11e8-8fe7-8c2d67a2a2bc.png)

It hung my OS several times until I removing it away.

**Comment by dmusican** [comment]
I experienced this same problem today.

**Comment by gabdub** [comment]
Same here. The system became totally unresponsive, I have to uninstall it.
UM18.04.1. Applet version: 1.5.1

**Comment by crypthora** [comment]
I experienced this same problem today too.

Please fix it!

**Comment by dseomn** [comment]
I also came across this bug, but I found a sort-of work around using the Command Applet and `xdotool`: https://github.com/dseomn/dotfiles/commit/a420996ea74a139d4a432147dab45697dbc2d4de

**Comment by MGdesigner** [comment]
> I also came across this bug, but I found a sort-of work around using the Command Applet and `xdotool`: [dseomn/dotfiles@a420996](https://github.com/dseomn/dotfiles/commit/a420996ea74a139d4a432147dab45697dbc2d4de)

It's a great job!! It works! Thanks for your solution!

**Comment by algiuxass** [comment]
This is important bug, please fix it! I had couple freezes on my Ubuntu MATE without knowing what happened. Just now I found that this applet was using 1.7GB, just to show window title?

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/ubuntu-mate/mate-window-applets/pull/8/commits/d959d6ace6c3de7ffe7ab71a97ac362ae3395081
